version: "3.9"
services:
  images_helper:
    build:
      context: .
      dockerfile: Dockerfile
    image: images_helper:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    mem_limit: 10g
    cpus: "4"
